apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: chatbox
resources:
  - ../../base
patches:
  - path: patches/replicas.yaml
  - path: patches/resources.yaml
  - path: patches/hpa.yaml
  - path: patches/pdb.yaml
  - path: patches/kong-service-lb.yaml
  - path: patches/image-pull-policy.yaml
images:
  - name: auth-service
    newName: docker.io/DOCKERHUB_USER/chatbox-auth-service
    newTag: latest
  - name: chat-service
    newName: docker.io/DOCKERHUB_USER/chatbox-chat-service
    newTag: latest
  - name: message-service
    newName: docker.io/DOCKERHUB_USER/chatbox-message-service
    newTag: latest
  - name: file-service
    newName: docker.io/DOCKERHUB_USER/chatbox-file-service
    newTag: latest
  - name: frontend
    newName: docker.io/DOCKERHUB_USER/chatbox-frontend
    newTag: latest
