apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: auth-service-pdb
  namespace: chatbox
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: auth-service
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: chat-service-pdb
  namespace: chatbox
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: chat-service
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: message-service-pdb
  namespace: chatbox
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: message-service
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: kong-pdb
  namespace: chatbox
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kong
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: frontend-pdb
  namespace: chatbox
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: frontend
