apiVersion: v1
kind: Namespace
metadata:
  name: chatbox-infra
  labels:
    app.kubernetes.io/part-of: chatbox
---
apiVersion: v1
kind: Namespace
metadata:
  name: chatbox-monitoring
  labels:
    app.kubernetes.io/part-of: chatbox
