apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: file-service
  namespace: chatbox
  labels:
    app.kubernetes.io/name: file-service
    app.kubernetes.io/part-of: chatbox
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: file-service
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s
