apiVersion: v1
kind: ConfigMap
metadata:
  name: chatbox-shared-config
  namespace: chatbox
  labels:
    app.kubernetes.io/part-of: chatbox
data:
  APP_ENV: "dev"
  CORS_ORIGINS: "http://localhost:30000,http://localhost:3000"
  KAFKA_BOOTSTRAP_SERVERS: "kafka.chatbox-infra.svc.cluster.local:9092"
  AUTH_SERVICE_URL: "http://auth-service:8001"
  MESSAGE_SERVICE_URL: "http://message-service:8004"
