apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
  namespace: chatbox
  labels:
    app.kubernetes.io/name: auth-service
    app.kubernetes.io/part-of: chatbox
data:
  PORT: "8001"
  LOG_LEVEL: "info"
