apiVersion: v1
kind: ConfigMap
metadata:
  name: file-service-config
  namespace: chatbox
  labels:
    app.kubernetes.io/name: file-service
    app.kubernetes.io/part-of: chatbox
data:
  UPLOAD_DIR: "./uploads"
  MAX_FILE_SIZE_BYTES: "157286400"
  PORT: "8005"
  NODE_ENV: "production"
