apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: chatbox
resources:
  - namespace.yaml
  - shared-config/
  - auth-service/
  - chat-service/
  - message-service/
  - file-service/
  - frontend/
  - kong/
