apiVersion: v1
kind: ConfigMap
metadata:
  name: message-service-config
  namespace: chatbox
  labels:
    app.kubernetes.io/name: message-service
    app.kubernetes.io/part-of: chatbox
data:
  PORT: "8004"
  LOG_LEVEL: "info"
