apiVersion: v1
kind: Service
metadata:
  name: message-service
  namespace: chatbox
  labels:
    app.kubernetes.io/name: message-service
    app.kubernetes.io/part-of: chatbox
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: message-service
  ports:
    - port: 8004
      targetPort: 8004
      protocol: TCP
