apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kong
  namespace: chatbox
  labels:
    app.kubernetes.io/name: kong
    app.kubernetes.io/part-of: chatbox
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kong
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s
