apiVersion: v1
kind: Secret
metadata:
  name: chat-service-secrets
  namespace: chatbox
  labels:
    app.kubernetes.io/name: chat-service
    app.kubernetes.io/part-of: chatbox
type: Opaque
stringData:
  DATABASE_URL: "postgresql://chatbox:CHANGE_ME@postgres-postgresql.chatbox-infra.svc.cluster.local:5432/chatbox_chat"
