"""add message_id column for kafka idempotent writes

Revision ID: 9b15123e7392
Revises: 062cbe6e6478
Create Date: 2026-03-19 20:50:39.493918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b15123e7392'
down_revision: Union[str, Sequence[str], None] = '062cbe6e6478'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('message_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_messages_message_id'), 'messages', ['message_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_message_id'), table_name='messages')
    op.drop_column('messages', 'message_id')
    # ### end Alembic commands ###
