apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: chatbox
  labels:
    app.kubernetes.io/name: auth-service
    app.kubernetes.io/part-of: chatbox
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: auth-service
  ports:
    - name: http
      port: 8001
      targetPort: 8001
      protocol: TCP
