apiVersion: v1
kind: Service
metadata:
  name: chat-service
  namespace: chatbox
  labels:
    app.kubernetes.io/name: chat-service
    app.kubernetes.io/part-of: chatbox
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: chat-service
  ports:
    - port: 8003
      targetPort: 8003
      protocol: TCP
